name: Deploy Infrastructure and Application

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"
    outputs:
      deployment_success: ${{ steps.set_deployment_status.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_flaskapp
          chmod 600 ~/.ssh/id_rsa_flaskapp
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa_flaskapp.pub
          chmod 644 ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa_flaskapp.pub
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init
        
      - name: Terraform Plan
        run: |
          cd infrastructure
          terraform plan

      - name: Terraform Apply
        id: terraform
        run: |
          cd infrastructure
          terraform apply -auto-approve
          
      - name: Get Terraform Output
        id: terraform_output
        run: |
          cd infrastructure
          # Store the output in a variable without debug messages
          IP=$(terraform output -raw public_ip 2>/dev/null | tr -d '\n')
          # Verify the IP is valid
          if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "instance_ip=$IP" >> $GITHUB_OUTPUT
            echo "instance_ip=$IP" >> $GITHUB_ENV
            echo "IP capturada: $IP"
          else
            echo "Error: Invalid IP format or Terraform output failed"
            exit 1
          fi

      - name: Update hosts.ini with new IP
        run: |
          cd infrastructure
          echo "[app_servers]" > hosts.ini
          echo "${{ steps.terraform_output.outputs.instance_ip || env.instance_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa_flaskapp ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> hosts.ini

      - name: Wait for SSH to be available
        run: |
          # Esperar a que la instancia esté lista para conexiones SSH
          echo "Esperando a que la instancia esté lista para SSH..."
          for i in {1..30}; do
            if ssh -i ~/.ssh/id_rsa_flaskapp -o StrictHostKeyChecking=no -o ConnectTimeout=5 ubuntu@${{ steps.terraform_output.outputs.instance_ip || env.instance_ip }} 'echo SSH ready'; then
              echo "SSH está listo!"
              break
            fi
            echo "Intento $i: SSH aún no está listo, esperando..."
            sleep 10
          done

      - name: Run Ansible Playbook
        id: ansible
        continue-on-error: true
        run: |
          cd infrastructure
          # Mostrar información de depuración
          echo "Contenido de hosts.ini:"
          cat hosts.ini
          echo "\nVerificando permisos de la clave SSH:"
          ls -la ~/.ssh/id_rsa_flaskapp
          # Ejecutar Ansible con modo verbose
          ansible-playbook -i hosts.ini deploy-with-docker.yml -vv
          
      - name: Set deployment status
        id: set_deployment_status
        run: |
          if [ "${{ steps.ansible.outcome }}" == "success" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Terraform Destroy on Failure
        if: steps.set_deployment_status.outputs.success != 'true'
        run: |
          echo "Deployment failed, destroying infrastructure..."
          cd infrastructure
          terraform destroy -auto-approve

  cleanup:
    needs: deploy
    if: failure() || needs.deploy.outputs.deployment_success != 'true'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
          
      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init
          
      - name: Terraform Destroy
        run: |
          cd infrastructure
          terraform destroy -auto-approve